export const DEMO_ACCOUNTS = {
  donor: {
    email: "demo.donor@donorix.in",
    password: "DemoDonor@2025",
    label: "Demo Donor Account",
    subtitle: "Auto-login into the donor workflow",
    redirectTo: "/find",
    profile: {
      full_name: "Demo Donor",
      username: "demo_donor",
      phone: "+919812345678",
      date_of_birth: "1998-06-14",
      gender: "male",
      blood_type: "O+",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110001",
      weight_kg: 72,
      has_chronic_disease: false,
      is_smoker: false,
      is_on_medication: false,
      preferred_language: "en",
      consent_terms: true,
      consent_privacy: true,
      consent_notifications: true,
      is_available: true,
      is_verified: true,
      karma: 120,
      total_donations: 0,
    },
  },
  hospital: {
    email: "demo.hospital@donorix.in",
    password: "DemoHospital@2025",
    label: "Demo Hospital Account",
    subtitle: "City Lifeline Hospital demo dashboard",
    redirectTo: "/",
    profile: {
      full_name: "City Lifeline Hospital",
      username: "city_lifeline_demo2025",
      phone: "+919876543210",
      gender: "prefer_not_to_say",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110001",
      preferred_language: "en",
      consent_terms: true,
      consent_privacy: true,
      consent_notifications: true,
      is_available: false,
      is_verified: true,
      karma: 0,
      total_donations: 0,
    },
    hospitalAccount: {
      hospital_name: "City Lifeline Hospital",
      hospital_type: "private_hospital",
      registration_number: "DEMO-REG-2025",
      address: "12 Ring Road, New Delhi, Delhi 110001",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110001",
      official_contact_email: "demo.hospital@donorix.in",
      official_contact_phone: "+919876543210",
      contact_person_name: "Demo Admin",
      verification_status: "verified",
    },
    metadata: {
      account_type: "hospital",
      email: "demo.hospital@donorix.in",
      phone: "+919876543210",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110001",
      preferred_language: "en",
      consent_terms: true,
      consent_privacy: true,
      consent_notifications: true,
      hospital_name: "City Lifeline Hospital",
      hospital_type: "private_hospital",
      registration_number: "DEMO-REG-2025",
      address: "12 Ring Road, New Delhi, Delhi 110001",
      contact_person_name: "Demo Admin",
      official_contact_email: "demo.hospital@donorix.in",
      official_contact_phone: "+919876543210",
      consent_hospital_verification: true,
    },
  },
} as const;

export const DEMO_ACCOUNT_EMAILS = [
  DEMO_ACCOUNTS.donor.email,
  DEMO_ACCOUNTS.hospital.email,
] as const;
