do $$
declare
  demo_hospital_user_id uuid := '11111111-1111-4111-8111-111111111111';
  demo_donor_user_id uuid := '22222222-2222-4222-8222-222222222222';
  demo_post_id uuid := '33333333-3333-4333-8333-333333333333';
  demo_hospital_email text := 'demo.hospital@donorix.in';
  demo_donor_email text := 'demo.donor@donorix.in';
begin
  delete from auth.identities
  where user_id in (demo_hospital_user_id, demo_donor_user_id);

  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    recovery_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  )
  values
    (
      '00000000-0000-0000-0000-000000000000',
      demo_hospital_user_id,
      'authenticated',
      'authenticated',
      demo_hospital_email,
      crypt('DemoHospital@2025', gen_salt('bf')),
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now()),
      '{"provider":"email","providers":["email"]}',
      jsonb_build_object(
        'account_type', 'hospital',
        'email', demo_hospital_email,
        'phone', '+919876543210',
        'city', 'New Delhi',
        'state', 'Delhi',
        'pincode', '110001',
        'preferred_language', 'en',
        'consent_terms', true,
        'consent_privacy', true,
        'consent_notifications', true,
        'hospital_name', 'City Lifeline Hospital',
        'hospital_type', 'private_hospital',
        'registration_number', 'DEMO-REG-2025',
        'address', '12 Ring Road, New Delhi, Delhi 110001',
        'contact_person_name', 'Demo Admin',
        'official_contact_email', demo_hospital_email,
        'official_contact_phone', '+919876543210',
        'consent_hospital_verification', true
      ),
      timezone('utc', now()),
      timezone('utc', now()),
      '',
      '',
      '',
      ''
    ),
    (
      '00000000-0000-0000-0000-000000000000',
      demo_donor_user_id,
      'authenticated',
      'authenticated',
      demo_donor_email,
      crypt('DemoDonor@2025', gen_salt('bf')),
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now()),
      '{"provider":"email","providers":["email"]}',
      jsonb_build_object(
        'account_type', 'donor',
        'full_name', 'Demo Donor',
        'username', 'demo_donor',
        'email', demo_donor_email,
        'phone', '+919812345678',
        'date_of_birth', '1998-06-14',
        'gender', 'male',
        'blood_type', 'O+',
        'city', 'New Delhi',
        'state', 'Delhi',
        'pincode', '110001',
        'weight_kg', 72,
        'has_chronic_disease', false,
        'is_smoker', false,
        'is_on_medication', false,
        'consent_terms', true,
        'consent_privacy', true,
        'consent_notifications', true
      ),
      timezone('utc', now()),
      timezone('utc', now()),
      '',
      '',
      '',
      ''
    )
  on conflict (id) do update
  set
    email = excluded.email,
    encrypted_password = excluded.encrypted_password,
    email_confirmed_at = excluded.email_confirmed_at,
    recovery_sent_at = excluded.recovery_sent_at,
    last_sign_in_at = excluded.last_sign_in_at,
    raw_app_meta_data = excluded.raw_app_meta_data,
    raw_user_meta_data = excluded.raw_user_meta_data,
    updated_at = timezone('utc', now());

  insert into auth.identities (
    provider_id,
    user_id,
    identity_data,
    provider,
    last_sign_in_at,
    created_at,
    updated_at
  )
  values
    (
      gen_random_uuid(),
      demo_hospital_user_id,
      jsonb_build_object(
        'sub', demo_hospital_user_id::text,
        'email', demo_hospital_email,
        'email_verified', true
      ),
      'email',
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now())
    ),
    (
      gen_random_uuid(),
      demo_donor_user_id,
      jsonb_build_object(
        'sub', demo_donor_user_id::text,
        'email', demo_donor_email,
        'email_verified', true
      ),
      'email',
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now())
    );

  insert into public.profiles (
    id,
    email,
    phone,
    full_name,
    username,
    account_type,
    blood_type,
    gender,
    date_of_birth,
    city,
    state,
    pincode,
    weight_kg,
    total_donations,
    karma,
    is_admin,
    is_available,
    is_verified,
    has_chronic_disease,
    is_smoker,
    is_on_medication,
    preferred_language,
    consent_terms,
    consent_privacy,
    consent_notifications,
    status,
    deleted_at,
    is_demo
  )
  values
    (
      demo_hospital_user_id,
      demo_hospital_email,
      '+919876543210',
      'City Lifeline Hospital',
      'city_lifeline_demo2025',
      'hospital',
      null,
      'prefer_not_to_say',
      null,
      'New Delhi',
      'Delhi',
      '110001',
      null,
      0,
      0,
      false,
      false,
      true,
      false,
      false,
      false,
      'en',
      true,
      true,
      true,
      'active',
      null,
      true
    ),
    (
      demo_donor_user_id,
      demo_donor_email,
      '+919812345678',
      'Demo Donor',
      'demo_donor',
      'donor',
      'O+',
      'male',
      '1998-06-14',
      'New Delhi',
      'Delhi',
      '110001',
      72,
      0,
      120,
      false,
      true,
      true,
      false,
      false,
      false,
      'en',
      true,
      true,
      true,
      'active',
      null,
      true
    )
  on conflict (id) do update
  set
    email = excluded.email,
    phone = excluded.phone,
    full_name = excluded.full_name,
    username = excluded.username,
    account_type = excluded.account_type,
    blood_type = excluded.blood_type,
    gender = excluded.gender,
    date_of_birth = excluded.date_of_birth,
    city = excluded.city,
    state = excluded.state,
    pincode = excluded.pincode,
    weight_kg = excluded.weight_kg,
    total_donations = excluded.total_donations,
    karma = excluded.karma,
    is_available = excluded.is_available,
    is_verified = excluded.is_verified,
    preferred_language = excluded.preferred_language,
    consent_terms = excluded.consent_terms,
    consent_privacy = excluded.consent_privacy,
    consent_notifications = excluded.consent_notifications,
    status = excluded.status,
    deleted_at = excluded.deleted_at,
    is_demo = excluded.is_demo,
    updated_at = timezone('utc', now());

  insert into public.hospital_accounts (
    profile_id,
    hospital_name,
    hospital_type,
    registration_number,
    address,
    city,
    state,
    pincode,
    official_contact_email,
    official_contact_phone,
    contact_person_name,
    verification_status
  )
  values (
    demo_hospital_user_id,
    'City Lifeline Hospital',
    'private_hospital',
    'DEMO-REG-2025',
    '12 Ring Road, New Delhi, Delhi 110001',
    'New Delhi',
    'Delhi',
    '110001',
    demo_hospital_email,
    '+919876543210',
    'Demo Admin',
    'verified'
  )
  on conflict (profile_id) do update
  set
    hospital_name = excluded.hospital_name,
    hospital_type = excluded.hospital_type,
    registration_number = excluded.registration_number,
    address = excluded.address,
    city = excluded.city,
    state = excluded.state,
    pincode = excluded.pincode,
    official_contact_email = excluded.official_contact_email,
    official_contact_phone = excluded.official_contact_phone,
    contact_person_name = excluded.contact_person_name,
    verification_status = excluded.verification_status,
    updated_at = timezone('utc', now());

  insert into public.posts (
    id,
    created_by,
    patient_name,
    patient_id,
    blood_type_needed,
    units_needed,
    hospital_name,
    hospital_address,
    city,
    state,
    contact_name,
    contact_phone,
    contact_email,
    medical_condition,
    additional_notes,
    is_emergency,
    required_by,
    initial_radius_km,
    current_radius_km,
    expires_at,
    status,
    priority_score,
    upvote_count,
    donor_count,
    sms_sent_count,
    is_demo
  )
  values (
    demo_post_id,
    demo_hospital_user_id,
    'Rahul Verma',
    'PATIENT-001',
    'O-',
    2,
    'City Lifeline Hospital',
    '12 Ring Road, New Delhi, Delhi 110001',
    'New Delhi',
    'Delhi',
    'Dr. Priya Sharma',
    '+919876543210',
    demo_hospital_email,
    'Post-operative blood loss following emergency appendectomy',
    'Emergency demo request created for stakeholder walkthroughs.',
    true,
    timezone('utc', now()) + interval '48 hours',
    25,
    25,
    timezone('utc', now()) + interval '72 hours',
    'active',
    999,
    0,
    0,
    0,
    true
  )
  on conflict (id) do update
  set
    created_by = excluded.created_by,
    patient_name = excluded.patient_name,
    patient_id = excluded.patient_id,
    blood_type_needed = excluded.blood_type_needed,
    units_needed = excluded.units_needed,
    hospital_name = excluded.hospital_name,
    hospital_address = excluded.hospital_address,
    city = excluded.city,
    state = excluded.state,
    contact_name = excluded.contact_name,
    contact_phone = excluded.contact_phone,
    contact_email = excluded.contact_email,
    medical_condition = excluded.medical_condition,
    additional_notes = excluded.additional_notes,
    is_emergency = excluded.is_emergency,
    required_by = excluded.required_by,
    initial_radius_km = excluded.initial_radius_km,
    current_radius_km = excluded.current_radius_km,
    expires_at = excluded.expires_at,
    status = excluded.status,
    priority_score = excluded.priority_score,
    is_demo = excluded.is_demo,
    updated_at = timezone('utc', now());
end
$$;
